import { msg } from "@lingui/core/macro";

export const Home = {
  HERO_TITLE: msg`Estes Executive Freight & LTL Hub`,
  HERO_SUBTITLE: msg`North America’s largest privately held freight transportation company. Track 17.6B+ lbs in shipment tonnage, 300+ terminal operations, and 51,000+ fleet assets.`,
  HERO_BADGE: msg`Estes Freight Analytics`,
  HERO_BADGE_SUFFIX: msg`Freight Analytics Platform`,
  ECOSYSTEM_CHECKOUT: msg`Freight Dispatch Stream`,
  ECOSYSTEM_INVENTORY: msg`Terminal Door Events`,
  ECOSYSTEM_SEMANTIC: msg`Looker Freight AI`,
  ECOSYSTEM_FABRIC_SUFFIX: msg`Freight Data Network`,
  ECOSYSTEM_REVENUE: msg`Live Freight Hub`,
  ECOSYSTEM_AI_REC: msg`LTL Route Recommendations`,
  ECOM_WIDGET_TITLE_SUFFIX: msg`Live Revenue Pulse`,
  ECOM_WIDGET_LIVE: msg`LIVE`,
  ECOM_WIDGET_TARGET: msg`+14.2% vs target`,
  ECOM_WIDGET_AOV_YIELD: msg`Shipment Yield`,
  SECTION_KPI_TITLE: msg`Live Financial & Fleet Summary`,
  KPI_REV_TITLE: msg`Total Freight Revenue`,
  KPI_REV_BADGE: msg`+14.2% vs last month`,
  KPI_ORD_TITLE: msg`Total Freight Shipments`,
  KPI_ORD_BADGE: msg`13.2M+ in 2025`,
  KPI_AOV_TITLE: msg`Avg Revenue per Shipment`,
  KPI_AOV_BADGE: msg`#1 Mastio Best Value`,
  FALLBACK_SALES: msg`Terminal Activity Stream`,
  FALLBACK_INSIGHTS: msg`AI Strategic Freight Briefing`,
  SECTION_APPS_TITLE: msg`Logistics & Analytical Portals`,
  APP_DASH_TITLE: msg`Operations Dashboard`,
  APP_DASH_DESC: msg`View embedded LTL shipping analytics, terminal door utilization, and fleet logistics reports.`,
  APP_CA_TITLE: msg`Conversational Freight Assistant`,
  APP_CA_DESC: msg`Interact with an AI assistant to query shipment status, terminal tonnage, and fleet metrics.`,
  APP_AGENTS_TITLE: msg`Freight AI Agents`,
  APP_AGENTS_DESC: msg`Manage and interact with Looker AI agents trained on Estes shipping and logistics data.`,
  APP_EXPLORE_TITLE: msg`Query Explorer`,
  APP_EXPLORE_DESC: msg`Build custom visual queries across terminal doors, drivers, tractors, and shipment routes.`,
  APP_REPORT_TITLE: msg`LTL Report Builder`,
  APP_REPORT_DESC: msg`Design custom freight reports, drag-and-drop logistics metrics, and terminal templates.`,
  RESOURCE_TITLE: msg`Estes Freight Network & 95-Year Legacy`,
  RESOURCE_SUBTITLE: msg`Founded 1931 in Richmond, VA. 95 years of steady growth with 24,000+ employees, 10,600+ tractors, and 300+ terminals across 50 states.`,
  RESOURCE_BTN: msg`Explore Estes Network`,
};
