import { msg } from "@lingui/core/macro";

export const SalesActivityFeed = {
  TITLE: msg`Live Fleet & Terminal Ticker`,
  SUBTITLE: msg`Real-time simulated Estes freight dispatch and terminal occurrences`,
  STATUS_TEXT: msg`Tracking Fleet Ticker`,
  ACT_1_TITLE: msg`LTL Freight Dispatch #12849 Finalized`,
  ACT_1_DESC: msg`LTL shipment dispatched containing 3,400 lbs of industrial freight across direct network.`,
  ACT_1_TIME: msg`Just now`,
  ACT_2_TITLE: msg`Terminal Door #42 Pickup Complete`,
  ACT_2_DESC: msg`Richmond Terminal door #42 loaded LTL trailers for mid-Atlantic delivery.`,
  ACT_2_TIME: msg`4m ago`,
  ACT_3_TITLE: msg`Linehaul Fleet Batch Dispatched`,
  ACT_3_DESC: msg`Terminal network dispatched 142 priority LTL freight shipments.`,
  ACT_3_TIME: msg`18m ago`,
  ACT_4_TITLE: msg`CNG Fleet Inspection Completed`,
  ACT_4_DESC: msg`Renewable natural gas tractor #8921 cleared safety inspection in Atlanta.`,
  ACT_4_TIME: msg`1h ago`,
  ACT_5_TITLE: msg`Terminal Door Capacity Alert`,
  ACT_5_DESC: msg`Terminal doors in Dallas operating at 92% peak capacity.`,
  ACT_5_TIME: msg`2h ago`,
  TAB_ALL: msg`All Stream`,
  TAB_REVENUE: msg`Revenue`,
  TAB_LOGISTICS: msg`Ops & Logistics`,
  TAB_ALERTS: msg`Alerts`,
  ACT_1_ACTION: msg`Dispatch #12849`,
  ACT_2_ACTION: msg`Richmond Terminal`,
  ACT_3_ACTION: msg`142 Dispatched`,
  ACT_4_ACTION: msg`CNG Tractor #8921`,
  ACT_5_ACTION: msg`Door Capacity Alert`,
};
